
language: node_js  #设置语言

node_js: stable  #设置相应的版本 
cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容
sudo: required


before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - npm install -g hexo-cli
  - npm install -g gulp  # 初次或删除缓存时取消注释

install:
  - npm install
  - npm install js-yaml --save-dev
  - npm install nodejieba --save-dev

script:
  - hexo clean
  - hexo g && gulp

after_script:
  - git clone https://${GH_REF} .deploy_git  # GH_REF是最下面配置的仓库地址
  - cd .deploy_git
  - git checkout master
  - cd ../
  - mv .deploy_git/.git/ ./public/   # 这一步之前的操作是为了保留master分支的提交记录，不然每次git init的话只有1条commit
  - cd ./public
  - git config user.name "kit.document@travis"  #修改name
  - git config user.email "me@tdouplus.com"  #修改email
  - git add .
  - git commit -m "Travis CI Auto Builder at `date +"%Y-%m-%d %H:%M"`"  # 提交记录包含时间 跟上面更改时区配合
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:gh-pages  #Travis_Token是在Travis中配置环境变量的名称
  - git push --force --quiet "https://${CODING_UNAME}:${CODING_TOKEN}@${CO_REF}" master:master #如果部署到coding上，这里的用户名也要修改


# deploy:
#   provider: pages
#   local-dir: public
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN
#   committer-from-gh: true
#   on:
#     branch: master

branches:
  only:
    - master

notifications:
  email:
    - me@tdouplus.com
  on_success: change
  on_failure: always
