# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: KyLin
author: kevin
language: zh-Hans
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'https://seed.catlib.io/child' and root as '/child/'
url: https://kylin.app
root: /

# Writing
relative_link: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ../node_modules/hexo-theme-cookbook



ignore:
  - '**/node_modules/**/*node_modules'

node_sass:
  includePaths:
   - node_modules

cookbook:
  favicon: favicon.ico
  partials:
    index:
      - _layout/index.ejs
  tag:
    anchor:
      default: core
      core: https://github.com/Kylin-Studio/Kit
  gitment:
    enable: true
    id: kylin-zh
    client_id: af6511a0afe81325b1b8
    client_secret: c9db5c29d06230d90add29cb40f7b26525084d6b
    github_owner: kevin
    github_user : gjmvvv
    github_repository: kylin.app
    per_page: 30
    maintainer:
      - yb199478

social:
  GitHub: https://github.com/gjmvvv
  Twitter: https://twitter.com/Kevin37233035
  Weibo: https://www.weibo.com/5730394625/


deploy:
  type: git
  repository: git@github.com:Kylin-Studio/kylin.app.git
  branch: "gh-pages"
  message: "Update Web"
