# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Kit 文档 | Unity 开发框架 & C# 开发工具包
author: TDou
language: zh-Hans
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'https://seed.catlib.io/child' and root as '/child/'
url: https://kit.tdouplus.com
root: /

# Writing
relative_link: false

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ../node_modules/hexo-theme-cookbook

# seo
baidu_push: true
baidusitemap: 
path: baidusitemap.xml

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

local_search:
  enable: true

ignore:
  - '**/node_modules/**/*node_modules'

node_sass:
  includePaths:
   - node_modules

cookbook:
  favicon: favicon.ico
  partials:
    index:
      - _layout/index.ejs
  tag:
    anchor:
      default: core
      core: https://github.com/T-dou/Kit
  gitment:
    enable: true
    id: '<%= page.title %>'
    client_id: af6511a0afe81325b1b8
    client_secret: c9db5c29d06230d90add29cb40f7b26525084d6b
    github_owner: T-Dou
    github_user : T-Dou
    github_repository:  
    per_page: 30
    maintainer:
      - yb199478

social:
  GitHub: https://github.com/T-Dou


# deploy:
#   type: git
#   repository: git@github.com:T-DOu/Kit.Document.git
#   branch: "gh-pages"
#   message: "deploy Auto Builder at `date +"%Y-%m-%d %H:%M"`"
